name: Actualizar JSON de Smartphones

# Ejecutar diariamente a las 03:00 UTC
on:
  schedule:
    - cron: '0 3 * * *'  # 03:00 UTC todos los días
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ejecutar script de actualización
      run: python update_json.py
    
    - name: Verificar cambios
      id: verify-changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit y push de cambios
      if: steps.verify-changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add smarphone500json.json
        git commit -m "Actualización automática del JSON"
        git push
    
    - name: Mostrar resumen
      run: |
        echo "✅ Workflow completado"
        echo "📅 Fecha: $(date)"
        echo "📊 Archivo actualizado: smarphone500json.json"
